[package]
name = "gravita-input"
description = "Input handling abstraction layer for Gravita game framework"
version = "0.1.0"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
keywords = ["input", "keyboard", "mouse", "gamepad", "gamedev"]
categories = ["game-engines"]

[lints]
workspace = true

[dependencies]
