# examples/bouncing-balls/Cargo.toml
[package]
name = "bouncing-balls"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
gravita-physics = { workspace = true }
gravita-math = { workspace = true }
gravita-renderer = { workspace = true }
gravita-example-shim = { workspace = true }

[[bin]]
name = "bouncing-balls"
path = "src/bouncing-balls.rs"
