[package]
name = "gravita-renderer-3d"
description = "wgpu-based 3D renderer + winit runner for the Gravita engine"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
gravita-input = { workspace = true }
gravita-math = { workspace = true }

bytemuck = "1.16"
pollster = "0.3"
wgpu = "0.19"
winit = { workspace = true }
